Clean up

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -20,14 +20,9 @@ done
 
 containerAppDir="/app/cmd/$app"
 
-invalid_platform() {
-  echo "Invalid platform"
-}
-
 case "$platform" in
   "linux") deploy_linux $containerAppDir ;;
   "js") deploy_js $containerAppDir ;;
   "wasm") deploy_wasm $containerAppDir ;;
-  *) invalid_platform
-    echo "Invalid platform" 1; exit 1 ;;
+  *) echo "Invalid platform" 1; exit 1 ;;
 esac
